#! /usr/bin/python3
#interpreter in the first line above

import math

#Programmer: Amin Hasanzadeh
#Date: September 3 2018
#Purpose: Learning basic operators: arithmatic, assignment, bitwise

MY_FIRST_INTEGER = 5
MY_SECOND_INTEGER = 3

MY_RESULT = MY_FIRST_INTEGER + MY_SECOND_INTEGER
print(MY_RESULT)
MY_RESULT = MY_FIRST_INTEGER - MY_SECOND_INTEGER
print(MY_RESULT)
MY_RESULT = MY_FIRST_INTEGER / MY_SECOND_INTEGER
print(MY_RESULT)
MY_RESULT = MY_FIRST_INTEGER * MY_SECOND_INTEGER
print(MY_RESULT)
MY_RESULT = MY_FIRST_INTEGER // MY_SECOND_INTEGER
print(MY_RESULT)
MY_RESULT = MY_FIRST_INTEGER ** MY_SECOND_INTEGER
print(MY_RESULT)
MY_RESULT += MY_FIRST_INTEGER
print(MY_RESULT)
MY_RESULT -= MY_SECOND_INTEGER
print(MY_RESULT)
MY_RESULT *= MY_FIRST_INTEGER
print(MY_RESULT)
MY_RESULT /= MY_SECOND_INTEGER
print(MY_RESULT)
MY_RESULT //= MY_SECOND_INTEGER
print(MY_RESULT)
MY_RESULT **= MY_SECOND_INTEGER
print(MY_RESULT)

MY_RESULT = bin(MY_FIRST_INTEGER)
print(MY_RESULT)
MY_RESULT = bin(MY_SECOND_INTEGER)
print(MY_RESULT)

MY_RESULT = MY_FIRST_INTEGER & MY_SECOND_INTEGER
MY_RESULT = bin(MY_RESULT)
print(MY_RESULT)

MY_RESULT = MY_FIRST_INTEGER | MY_SECOND_INTEGER
MY_RESULT = bin(MY_RESULT)
print(MY_RESULT)


MY_RESULT = ~MY_FIRST_INTEGER   #Nagate
MY_RESULT = bin(MY_RESULT)
print(MY_RESULT)

MY_RESULT = MY_FIRST_INTEGER << MY_SECOND_INTEGER    #Shift
MY_RESULT = bin(MY_RESULT)
print(MY_RESULT)

MY_RESULT = MY_FIRST_INTEGER >> MY_SECOND_INTEGER
MY_RESULT = bin(MY_RESULT)
print(MY_RESULT)

MY_FIRST_NUMBER = math.pi
print(MY_FIRST_NUMBER)
MY_SECOND_NUMBER = math.sin(MY_FIRST_NUMBER)    #Radian
print(MY_SECOND_NUMBER)

